title: Project or Site name
tagline: A responsive theme for your project on GitHub Pages
baseurl: ''
paginate: 1
locale: en
author:
  name: Author name
  url: 'http://yourhomepage.com'
gems:
  - jekyll-paginate
markdown: kramdown
url: ''
